import assert from 'node:assert/strict';
import { randomUUID } from 'node:crypto';
import test from 'node:test';
import pg from 'pg';
import { AnalyticsService } from '../dist/review/analytics.service.js';
import { ValidationAuthoringService } from '../dist/admin/validation-authoring.service.js';
import { CanonicalPackageService } from '../dist/admin/canonical-package.service.js';
import { makePackage } from '../dist/admin/canonical-package.js';
import { CatalogAuthoringService } from '../dist/admin/catalog-authoring.service.js';
import { configuredAnalyticsLibrary, contributeConfiguredDefinition } from '../dist/review/analytics-definitions.js';
import { readValidationDefinition } from '@open-triage/contracts';

test('metrics share save, publication, clone, activation, canonical transfer and history in PostgreSQL', { skip: !process.env.DATABASE_URL }, async (t) => {
  const client = new pg.Client({ connectionString: process.env.DATABASE_URL }); await client.connect();
  try {
    await client.query('begin isolation level serializable');
    const { rows: [active] } = await client.query('select * from app_identity.active_configuration_bundle limit 1');
    assert.ok(active, 'An ordinary local installation is required');
    const actor = randomUUID(), metricId = randomUUID(), ruleId = randomUUID();
    await client.query(`insert into app_identity.app_user(id,organization_id,display_name,synthetic) values($1,$2,'Metric rollback verification',true)`, [actor,active.organization_id]);
    const query = async (sql, params) => (await client.query(sql,params)).rows;
    const manager = { query }, db = { query, manager, transaction: async (...args) => args.at(-1)(manager) };
    const capabilities = [];
    const sessions = { requireCapability: async (_token, capability) => { capabilities.push(capability); return { organization:{id:active.organization_id},user:{id:actor} }; } };
    const service = new ValidationAuthoringService(db,sessions);
    const catalogs = new CatalogAuthoringService(db,sessions);
    const canonical = new CanonicalPackageService(db,sessions,catalogs,{},service); canonical.persist = async () => {};
    const metric = { id:metricId,name:'PSAP to patient',description:'Rollback verification',enabled:true,reviewEnabled:true,unit:'s',source:JSON.stringify({operator:'elapsed',start:{operator:'timestamp',elementId:'eTimes.01'},end:{operator:'timestamp',elementId:'eTimes.07'},unit:'s'}) };
    const rule = { id:ruleId,name:'Interval check',message:'Interval exceeded',enabled:true,severity:'none',reviewPriority:'none',executionTargets:['review'],primaryTargetElementId:'eTimes.07',source:`require metricCompare("${metricId}", "less-or-equal", 90, "s")` };
    const draft = await service.create('test',{catalogReleaseId:active.catalog_release_id,displayName:'Metric integration'}, {importedRules:[rule],importedMetrics:[metric]});
    assert.equal(draft.metrics[0].id,metricId);
    await assert.rejects(service.save('test',draft.id,{expectedRevision:99,displayName:draft.displayName,rules:draft.rules,metrics:draft.metrics}),/stale/);
    await assert.rejects(service.save('test',draft.id,{expectedRevision:draft.revision,displayName:draft.displayName,rules:draft.rules,metrics:[]}),/disabled rather than removed/);
    const saved = await service.save('test',draft.id,{expectedRevision:draft.revision,displayName:draft.displayName,rules:draft.rules,metrics:draft.metrics});
    const valid = await service.validate('test',saved.id); assert.equal(valid.valid,true,JSON.stringify(valid.diagnostics));
    assert.equal(valid.compiledBundle.schemaVersion,2);
    const published = await service.publish('test',saved.id,{expectedRevision:saved.revision,displayName:saved.displayName,changeNote:'Integration test'});
    const exported = await canonical.export('test','validation',published.id);
    assert.equal(exported.schemaVersion,2); assert.equal(exported.definition.metrics[0].id,metricId);
    const { rows: [unchanged] } = await client.query('select * from app_identity.active_configuration_bundle where organization_id=$1',[active.organization_id]);
    assert.equal(unchanged.validation_version_id,active.validation_version_id);
    await service.activate('test',published.id,{formVersionId:active.form_version_id,catalogReleaseId:active.catalog_release_id,changeNote:'Integration activation'});
    const scope = {organizationId:active.organization_id,userId:actor,reports:'all',identifying:true,administrator:true,defaultDataset:'synthetic'};
    const library = await configuredAnalyticsLibrary(manager,scope);
    assert.equal(library.elements.length,2); assert.ok(library.elements.some((entry)=>entry.configured.kind==='rule'));
    assert.equal(library.elements[0].recordCount,0);
    const cloned = await service.clone('test',published.id,{catalogReleaseId:active.catalog_release_id,displayName:'Metric-only edit'});
    assert.equal(cloned.metrics[0].id,metricId);
    const edited = await service.save('test',cloned.id,{expectedRevision:cloned.revision,displayName:cloned.displayName,rules:cloned.rules,metrics:[{...cloned.metrics[0],description:'Changed only metric'}]});
    const next = await service.publish('test',edited.id,{expectedRevision:edited.revision,displayName:edited.displayName,changeNote:'Metric-only publication'});
    assert.ok(next.version>published.version); assert.notEqual(next.sourceSha256,published.sourceSha256);
    const events = await service.history('test'); assert.ok(events.find((event)=>event.destinationVersionId===next.id).ruleChanges.metrics.modifications.includes(metricId));
    const original = (await query('select source_rule from validation.version where id=$1',[published.id]))[0];
    assert.equal(readValidationDefinition(original.source_rule).metrics[0].description,metric.description);
    const imported = await canonical.import('test','validation',exported,active.catalog_release_id);
    const importedExport = await canonical.export('test','validation',imported.id);
    assert.equal(importedExport.definition.metrics[0].id,metricId);
    assert.notEqual(importedExport.definition.rules[0].id,ruleId);
    assert.ok(importedExport.definition.rules[0].source.includes(metricId));
    const metricOnlyPackage = makePackage({kind:'validation',name:'Metric only',version:'1',catalog:exported.catalog,
      definition:{schemaVersion:2,rules:[],metrics:[metric]}});
    const metricOnly = await canonical.import('test','validation',metricOnlyPackage,active.catalog_release_id);
    const metricOnlyExport = await canonical.export('test','validation',metricOnly.id);
    assert.deepEqual(metricOnlyExport.definition.rules,[]); assert.equal(metricOnlyExport.definition.metrics.length,1);
    assert.deepEqual(metricOnly.ruleIds,[]);
    assert.ok(capabilities.includes('validation:write')&&capabilities.includes('validation:publish'));
    const foreign = await configuredAnalyticsLibrary(manager,{...scope,organizationId:randomUUID()}); assert.equal(foreign.elements.length,0);
    // Analyze existing authorized signed reports without creating Review work.
    const signed = await query(`select id,reporting_date::text,revision::text from clinical.report where organization_id=$1 and synthetic and status='signed' and (expires_at is null or expires_at>now()) limit 2`,[active.organization_id]);
    const count = async () => (await query('select count(*)::int count from clinical.review_work where organization_id=$1',[active.organization_id]))[0].count;
    const before = await count();
    await client.query('set local role open_triage_api_runtime');
    if (signed.length) {
      const reports = signed.map((row)=>({id:row.id,date:row.reporting_date,revision:row.revision,values:[]}));
      await contributeConfiguredDefinition(manager,scope,reports,library.elements[0],library);
      assert.equal(reports[0].values.length,1); assert.ok(reports[0].values[0].evidence.definition.validationVersionId===published.id);
      const reporting = { query: async (sql, params) => sql.includes('projection_health') ? [{ observed_at: new Date('2026-10-04T00:00:00Z'),
        oldest_backlog_age_seconds:null,persistent_failure_count:0,retrying_count:0,stale_run_count:0,last_run_status:'succeeded',is_read_only_replica:false,replay_lag_seconds:null }] : query(sql,params) };
      const analyticsDb = { ...reporting, transaction: async (_level,work) => work(reporting) };
      let session = { organization:{id:active.organization_id},user:{id:actor},capabilities:['review:all','clinical:demo','review:identifying'] };
      const analytics = new AnalyticsService(analyticsDb,{get:async()=>session},{analyticsDatabase:async()=>analyticsDb});
      const selection = {version:1,metric:library.elements[0].id,aggregation:'p90',visualization:'table',from:signed[0].reporting_date,through:signed[0].reporting_date,groupBy:null,timeGrouping:'day',filters:[]};
      const result = await analytics.query('test',selection);
      assert.ok(result.completeness.total>0); assert.equal(result.metric.configured.validationVersionId,published.id);
      assert.equal(result.evidence.length,result.completeness.total);
      assert.ok(result.evidence.every(row=>row.evaluation.definition.validationVersionId===published.id));
      const csv = await analytics.export('test',{definition:selection,expectedRevision:result.exportRevision,kind:'records'});
      assert.ok(csv.includes(metricId)); assert.ok(csv.includes('nearest rank'));
      const outcome = await analytics.query('test',{...selection,metric:library.elements.find(element=>element.configured.kind==='rule').id,aggregation:'percentage',outcome:'fail'});
      assert.ok(outcome.cells.every(cell=>cell.denominator===cell.valid));
      session = {...session,capabilities:['review:self','clinical:demo']};
      assert.equal((await analytics.query('test',selection)).completeness.total,0);
      assert.equal((await analytics.elements('test','PSAP to patient')).total,1,'configuration discovery is independent of empty readable history');
      session = {...session,organization:{id:randomUUID()}};
      assert.equal((await analytics.elements('test','PSAP to patient')).total,0);
      await client.query('reset role');
      await service.activate('test',next.id,{formVersionId:active.form_version_id,catalogReleaseId:active.catalog_release_id,changeNote:'Test export version binding'});
      session = {...session,organization:{id:active.organization_id},capabilities:['review:all','clinical:demo','review:identifying']};
      await assert.rejects(analytics.export('test',{definition:selection,expectedRevision:result.exportRevision,kind:'records'}),error=>error.status===409);
      await service.activate('test',published.id,{formVersionId:active.form_version_id,catalogReleaseId:active.catalog_release_id,changeNote:'Test rollback restores both libraries'});
      assert.equal((await configuredAnalyticsLibrary(manager,scope)).elements[0].configured.validationVersionId,published.id);
    } else t.diagnostic('No synthetic signed reports available for contribution integration');
    assert.equal(await count(),before);
  } finally { await client.query('rollback'); await client.end(); }
});
