/* Generated by scripts/generate-nemsis-ems-import.mjs from the pinned official source. */
import type { NemsisNormalizationTable } from "./nemsis-schematron-import.js";

export const NEMSIS_351_EMS_SOURCE_SHA256 = "b096fadc0efb1606dbee4d55d610562e895a6a2dbac0c3a622bf43f72196b8c2" as const;
export const NEMSIS_351_EMS_NORMALIZATIONS = {
  "nemSch_e003": {
    "primaryTargetElementId": "eSituation.01",
    "source": "when hasPertinentNegative(\"eSituation.01\", \"8801023\")\nrequire all(emptyPayload(\"eSituation.01\"), not(hasNotValue(\"eSituation.01\")))"
  },
  "nemSch_e188": {
    "primaryTargetElementId": "eSituation.18",
    "source": "when hasPertinentNegative(\"eSituation.18\", \"8801023\")\nrequire all(emptyPayload(\"eSituation.18\"), not(hasNotValue(\"eSituation.18\")))"
  },
  "nemSch_e189": {
    "primaryTargetElementId": "eArrest.14",
    "source": "when hasPertinentNegative(\"eArrest.14\", \"8801023\")\nrequire all(emptyPayload(\"eArrest.14\"), not(hasNotValue(\"eArrest.14\")))"
  },
  "nemSch_e190": {
    "primaryTargetElementId": "ePatient.15",
    "source": "for each(\"ePatient.AgeGroup\")\nwhen hasPertinentNegative(\"ePatient.15\", \"8801029\")\nrequire all(not(emptyPayload(\"ePatient.15\")), not(hasNotValue(\"ePatient.15\")))"
  },
  "nemSch_e004": {
    "primaryTargetElementId": "eSituation.01",
    "source": "when hasPertinentNegative(\"eSituation.01\", \"8801029\")\nrequire all(not(emptyPayload(\"eSituation.01\")), not(hasNotValue(\"eSituation.01\")))"
  },
  "nemSch_e191": {
    "primaryTargetElementId": "eSituation.18",
    "source": "when hasPertinentNegative(\"eSituation.18\", \"8801029\")\nrequire all(not(emptyPayload(\"eSituation.18\")), not(hasNotValue(\"eSituation.18\")))"
  },
  "nemSch_e192": {
    "primaryTargetElementId": "eArrest.14",
    "source": "when hasPertinentNegative(\"eArrest.14\", \"8801029\")\nrequire all(not(emptyPayload(\"eArrest.14\")), not(hasNotValue(\"eArrest.14\")))"
  },
  "nemSch_e005": {
    "primaryTargetElementId": "eSituation.10",
    "source": "when hasPertinentNegative(\"eSituation.10\")\nrequire all(not(emptyPayload(\"eSituation.10\")), not(hasNotValue(\"eSituation.10\")))"
  },
  "nemSch_e006": {
    "primaryTargetElementId": "eMedications.03",
    "source": "for each(\"eMedications.MedicationGroup\")\nwhen hasPertinentNegative(\"eMedications.03\")\nrequire all(not(emptyPayload(\"eMedications.03\")), not(hasNotValue(\"eMedications.03\")))"
  },
  "nemSch_e007": {
    "primaryTargetElementId": "eProcedures.03",
    "source": "for each(\"eProcedures.ProcedureGroup\")\nwhen hasPertinentNegative(\"eProcedures.03\")\nrequire all(not(emptyPayload(\"eProcedures.03\")), not(hasNotValue(\"eProcedures.03\")))"
  },
  "nemSch_e008": {
    "primaryTargetElementId": "*",
    "source": "require allElements(\"pn-needs-empty-no-nv\", \"eCustomResults.01\", \"eExam.01\", \"eExam.02\", \"eExam.03\", \"eExam.04\", \"eExam.05\", \"eExam.06\", \"eExam.07\", \"eExam.09\", \"eExam.10\", \"eExam.11\", \"eExam.12\", \"eExam.13\", \"eExam.14\", \"eExam.15\", \"eExam.16\", \"eExam.17\", \"eExam.18\", \"eExam.19\", \"eExam.20\", \"eExam.21\", \"eExam.22\", \"eExam.23\", \"eExam.24\", \"eExam.25\", \"eHistory.10\", \"eSituation.01\", \"eSituation.18\", \"eArrest.14\", \"ePatient.15\", \"eSituation.10\", \"eMedications.03\", \"eProcedures.03\")"
  },
  "nemSch_e001": {
    "primaryTargetElementId": "*",
    "source": "require allElements(\"nil-needs-absence\", \"eCustomResults.01\")"
  },
  "nemSch_e002": {
    "primaryTargetElementId": "*",
    "source": "require allElements(\"nv-needs-empty\", \"eCustomResults.01\", \"eExam.01\", \"eExam.02\", \"eExam.03\", \"eExam.04\", \"eExam.05\", \"eExam.06\", \"eExam.07\", \"eExam.09\", \"eExam.10\", \"eExam.11\", \"eExam.12\", \"eExam.13\", \"eExam.14\", \"eExam.15\", \"eExam.16\", \"eExam.17\", \"eExam.18\", \"eExam.19\", \"eExam.20\", \"eExam.21\", \"eExam.22\", \"eExam.23\", \"eExam.24\", \"eExam.25\", \"eHistory.10\", \"eSituation.01\", \"eSituation.18\", \"eArrest.14\", \"ePatient.15\", \"eSituation.10\", \"eMedications.03\", \"eProcedures.03\")"
  },
  "nemSch_e009": {
    "primaryTargetElementId": "*",
    "source": "require allElements(\"unique-nv\", \"eCustomResults.01\")"
  },
  "nemSch_e010": {
    "primaryTargetElementId": "*",
    "source": "require allElements(\"unique-pn\", \"eCustomResults.01\", \"eExam.01\", \"eExam.02\", \"eExam.03\", \"eExam.04\", \"eExam.05\", \"eExam.06\", \"eExam.07\", \"eExam.09\", \"eExam.10\", \"eExam.11\", \"eExam.12\", \"eExam.13\", \"eExam.14\", \"eExam.15\", \"eExam.16\", \"eExam.17\", \"eExam.18\", \"eExam.19\", \"eExam.20\", \"eExam.21\", \"eExam.22\", \"eExam.23\", \"eExam.24\", \"eExam.25\", \"eHistory.10\", \"eSituation.01\", \"eSituation.18\", \"eArrest.14\", \"ePatient.15\", \"eSituation.10\", \"eMedications.03\", \"eProcedures.03\")"
  },
  "nemSch_e011": {
    "primaryTargetElementId": "eResponse.01",
    "source": "require compare(\"eResponse.01\", \"equal\", \"dAgency.02\")"
  },
  "nemSch_e012": {
    "primaryTargetElementId": "eResponse.08",
    "source": "when compareValue(\"eResponse.08\", \"equal\", \"2208013\")\nrequire all(minimum(\"eResponse.08\", 1), maximum(\"eResponse.08\", 1))"
  },
  "nemSch_e013": {
    "primaryTargetElementId": "eResponse.09",
    "source": "when compareValue(\"eResponse.09\", \"equal\", \"2209011\")\nrequire all(minimum(\"eResponse.09\", 1), maximum(\"eResponse.09\", 1))"
  },
  "nemSch_e014": {
    "primaryTargetElementId": "eResponse.10",
    "source": "when compareValue(\"eResponse.10\", \"equal\", \"2210017\")\nrequire all(minimum(\"eResponse.10\", 1), maximum(\"eResponse.10\", 1))"
  },
  "nemSch_e015": {
    "primaryTargetElementId": "eResponse.11",
    "source": "when compareValue(\"eResponse.11\", \"equal\", \"2211011\")\nrequire all(minimum(\"eResponse.11\", 1), maximum(\"eResponse.11\", 1))"
  },
  "nemSch_e016": {
    "primaryTargetElementId": "eResponse.12",
    "source": "when compareValue(\"eResponse.12\", \"equal\", \"2212015\")\nrequire all(minimum(\"eResponse.12\", 1), maximum(\"eResponse.12\", 1))"
  },
  "nemSch_e017": {
    "primaryTargetElementId": "eTimes.03",
    "source": "when not(any(undocumented(\"eTimes.03\"), emptyPayload(\"eTimes.03\")))\nrequire any(any(undocumented(\"eTimes.01\"), emptyPayload(\"eTimes.01\")), timeCompare(\"eTimes.03\", \"same-or-after\", \"eTimes.01\"))"
  },
  "nemSch_e018": {
    "primaryTargetElementId": "eTimes.05",
    "source": "when any(undocumented(\"eTimes.05\"), emptyPayload(\"eTimes.05\"))\nrequire compareValue(\"eDisposition.27\", \"equal\", \"4227005\")"
  },
  "nemSch_e019": {
    "primaryTargetElementId": "eTimes.05",
    "source": "when not(any(undocumented(\"eTimes.05\"), emptyPayload(\"eTimes.05\")))\nrequire timeCompare(\"eTimes.05\", \"same-or-after\", \"eTimes.03\")"
  },
  "nemSch_e020": {
    "primaryTargetElementId": "eTimes.06",
    "source": "when any(undocumented(\"eTimes.06\"), emptyPayload(\"eTimes.06\"))\nrequire compareValue(\"eDisposition.27\", \"equal\", \"4227005\")"
  },
  "nemSch_e021": {
    "primaryTargetElementId": "eTimes.06",
    "source": "when not(any(undocumented(\"eTimes.06\"), emptyPayload(\"eTimes.06\")))\nrequire timeCompare(\"eTimes.06\", \"same-or-after\", \"eTimes.03\")"
  },
  "nemSch_e022": {
    "primaryTargetElementId": "eTimes.06",
    "source": "when not(any(undocumented(\"eTimes.06\"), emptyPayload(\"eTimes.06\")))\nrequire any(any(undocumented(\"eTimes.05\"), emptyPayload(\"eTimes.05\")), timeCompare(\"eTimes.06\", \"same-or-after\", \"eTimes.05\"))"
  },
  "nemSch_e023": {
    "primaryTargetElementId": "eTimes.07",
    "source": "when any(undocumented(\"eTimes.07\"), emptyPayload(\"eTimes.07\"))\nrequire compareValue(\"eDisposition.27\", \"not-equal\", \"4227001\")"
  },
  "nemSch_e024": {
    "primaryTargetElementId": "eTimes.07",
    "source": "when not(any(undocumented(\"eTimes.07\"), emptyPayload(\"eTimes.07\")))\nrequire timeCompare(\"eTimes.07\", \"same-or-after\", \"eTimes.03\")"
  },
  "nemSch_e025": {
    "primaryTargetElementId": "eTimes.09",
    "source": "when any(undocumented(\"eTimes.09\"), emptyPayload(\"eTimes.09\"))\nrequire compareValue(\"eDisposition.27\", \"equal\", \"4227005\")"
  },
  "nemSch_e026": {
    "primaryTargetElementId": "eTimes.09",
    "source": "when not(any(undocumented(\"eTimes.09\"), emptyPayload(\"eTimes.09\")))\nrequire timeCompare(\"eTimes.09\", \"same-or-after\", \"eTimes.03\")"
  },
  "nemSch_e027": {
    "primaryTargetElementId": "eTimes.09",
    "source": "when not(any(undocumented(\"eTimes.09\"), emptyPayload(\"eTimes.09\")))\nrequire any(any(undocumented(\"eTimes.05\"), emptyPayload(\"eTimes.05\")), timeCompare(\"eTimes.09\", \"same-or-after\", \"eTimes.05\"))"
  },
  "nemSch_e028": {
    "primaryTargetElementId": "eTimes.09",
    "source": "when not(any(undocumented(\"eTimes.09\"), emptyPayload(\"eTimes.09\")))\nrequire any(any(undocumented(\"eTimes.06\"), emptyPayload(\"eTimes.06\")), timeCompare(\"eTimes.09\", \"same-or-after\", \"eTimes.06\"))"
  },
  "nemSch_e029": {
    "primaryTargetElementId": "eTimes.09",
    "source": "when not(any(undocumented(\"eTimes.09\"), emptyPayload(\"eTimes.09\")))\nrequire any(any(undocumented(\"eTimes.07\"), emptyPayload(\"eTimes.07\")), timeCompare(\"eTimes.09\", \"same-or-after\", \"eTimes.07\"))"
  },
  "nemSch_e030": {
    "primaryTargetElementId": "eTimes.11",
    "source": "when any(undocumented(\"eTimes.11\"), emptyPayload(\"eTimes.11\"))\nrequire not(member(\"eDisposition.30\", \"4230001\", \"4230003\"))"
  },
  "nemSch_e031": {
    "primaryTargetElementId": "eTimes.11",
    "source": "when not(any(undocumented(\"eTimes.11\"), emptyPayload(\"eTimes.11\")))\nrequire timeCompare(\"eTimes.11\", \"same-or-after\", \"eTimes.03\")"
  },
  "nemSch_e032": {
    "primaryTargetElementId": "eTimes.11",
    "source": "when not(any(undocumented(\"eTimes.11\"), emptyPayload(\"eTimes.11\")))\nrequire any(any(undocumented(\"eTimes.05\"), emptyPayload(\"eTimes.05\")), timeCompare(\"eTimes.11\", \"same-or-after\", \"eTimes.05\"))"
  },
  "nemSch_e033": {
    "primaryTargetElementId": "eTimes.11",
    "source": "when not(any(undocumented(\"eTimes.11\"), emptyPayload(\"eTimes.11\")))\nrequire any(any(undocumented(\"eTimes.06\"), emptyPayload(\"eTimes.06\")), timeCompare(\"eTimes.11\", \"same-or-after\", \"eTimes.06\"))"
  },
  "nemSch_e034": {
    "primaryTargetElementId": "eTimes.11",
    "source": "when not(any(undocumented(\"eTimes.11\"), emptyPayload(\"eTimes.11\")))\nrequire any(any(undocumented(\"eTimes.07\"), emptyPayload(\"eTimes.07\")), timeCompare(\"eTimes.11\", \"same-or-after\", \"eTimes.07\"))"
  },
  "nemSch_e035": {
    "primaryTargetElementId": "eTimes.11",
    "source": "when not(any(undocumented(\"eTimes.11\"), emptyPayload(\"eTimes.11\")))\nrequire any(any(undocumented(\"eTimes.09\"), emptyPayload(\"eTimes.09\")), timeCompare(\"eTimes.11\", \"same-or-after\", \"eTimes.09\"))"
  },
  "nemSch_e036": {
    "primaryTargetElementId": "eTimes.12",
    "source": "when any(undocumented(\"eTimes.12\"), emptyPayload(\"eTimes.12\"))\nrequire not(member(\"eDisposition.30\", \"4230001\", \"4230003\"))"
  },
  "nemSch_e037": {
    "primaryTargetElementId": "eTimes.12",
    "source": "when not(any(undocumented(\"eTimes.12\"), emptyPayload(\"eTimes.12\")))\nrequire timeCompare(\"eTimes.12\", \"same-or-after\", \"eTimes.03\")"
  },
  "nemSch_e038": {
    "primaryTargetElementId": "eTimes.12",
    "source": "when not(any(undocumented(\"eTimes.12\"), emptyPayload(\"eTimes.12\")))\nrequire any(any(undocumented(\"eTimes.05\"), emptyPayload(\"eTimes.05\")), timeCompare(\"eTimes.12\", \"same-or-after\", \"eTimes.05\"))"
  },
  "nemSch_e039": {
    "primaryTargetElementId": "eTimes.12",
    "source": "when not(any(undocumented(\"eTimes.12\"), emptyPayload(\"eTimes.12\")))\nrequire any(any(undocumented(\"eTimes.06\"), emptyPayload(\"eTimes.06\")), timeCompare(\"eTimes.12\", \"same-or-after\", \"eTimes.06\"))"
  },
  "nemSch_e040": {
    "primaryTargetElementId": "eTimes.12",
    "source": "when not(any(undocumented(\"eTimes.12\"), emptyPayload(\"eTimes.12\")))\nrequire any(any(undocumented(\"eTimes.07\"), emptyPayload(\"eTimes.07\")), timeCompare(\"eTimes.12\", \"same-or-after\", \"eTimes.07\"))"
  },
  "nemSch_e041": {
    "primaryTargetElementId": "eTimes.12",
    "source": "when not(any(undocumented(\"eTimes.12\"), emptyPayload(\"eTimes.12\")))\nrequire any(any(undocumented(\"eTimes.09\"), emptyPayload(\"eTimes.09\")), timeCompare(\"eTimes.12\", \"same-or-after\", \"eTimes.09\"))"
  },
  "nemSch_e042": {
    "primaryTargetElementId": "eTimes.12",
    "source": "when not(any(undocumented(\"eTimes.12\"), emptyPayload(\"eTimes.12\")))\nrequire any(any(undocumented(\"eTimes.11\"), emptyPayload(\"eTimes.11\")), timeCompare(\"eTimes.12\", \"same-or-after\", \"eTimes.11\"))"
  },
  "nemSch_e043": {
    "primaryTargetElementId": "eTimes.12",
    "source": "when not(any(undocumented(\"eTimes.12\"), emptyPayload(\"eTimes.12\")))\nrequire any(any(undocumented(\"eSituation.01\"), emptyPayload(\"eSituation.01\")), timeCompare(\"eTimes.12\", \"same-or-after\", \"eSituation.01\"))"
  },
  "nemSch_e044": {
    "primaryTargetElementId": "eTimes.12",
    "source": "when not(any(undocumented(\"eTimes.12\"), emptyPayload(\"eTimes.12\")))\nrequire any(any(undocumented(\"eSituation.18\"), emptyPayload(\"eSituation.18\")), timeCompare(\"eTimes.12\", \"same-or-after\", \"eSituation.18\"))"
  },
  "nemSch_e045": {
    "primaryTargetElementId": "eTimes.12",
    "source": "when not(any(undocumented(\"eTimes.12\"), emptyPayload(\"eTimes.12\")))\nrequire any(any(undocumented(\"eArrest.14\"), emptyPayload(\"eArrest.14\")), timeCompare(\"eTimes.12\", \"same-or-after\", \"eArrest.14\"))"
  },
  "nemSch_e046": {
    "primaryTargetElementId": "eTimes.13",
    "source": "when not(any(undocumented(\"eTimes.13\"), emptyPayload(\"eTimes.13\")))\nrequire timeCompare(\"eTimes.13\", \"same-or-after\", \"eTimes.03\")"
  },
  "nemSch_e047": {
    "primaryTargetElementId": "eTimes.13",
    "source": "when not(any(undocumented(\"eTimes.13\"), emptyPayload(\"eTimes.13\")))\nrequire any(any(undocumented(\"eTimes.05\"), emptyPayload(\"eTimes.05\")), timeCompare(\"eTimes.13\", \"same-or-after\", \"eTimes.05\"))"
  },
  "nemSch_e048": {
    "primaryTargetElementId": "eTimes.13",
    "source": "when not(any(undocumented(\"eTimes.13\"), emptyPayload(\"eTimes.13\")))\nrequire any(any(undocumented(\"eTimes.06\"), emptyPayload(\"eTimes.06\")), timeCompare(\"eTimes.13\", \"same-or-after\", \"eTimes.06\"))"
  },
  "nemSch_e049": {
    "primaryTargetElementId": "eTimes.13",
    "source": "when not(any(undocumented(\"eTimes.13\"), emptyPayload(\"eTimes.13\")))\nrequire any(any(undocumented(\"eTimes.07\"), emptyPayload(\"eTimes.07\")), timeCompare(\"eTimes.13\", \"same-or-after\", \"eTimes.07\"))"
  },
  "nemSch_e050": {
    "primaryTargetElementId": "eTimes.13",
    "source": "when not(any(undocumented(\"eTimes.13\"), emptyPayload(\"eTimes.13\")))\nrequire any(any(undocumented(\"eTimes.09\"), emptyPayload(\"eTimes.09\")), timeCompare(\"eTimes.13\", \"same-or-after\", \"eTimes.09\"))"
  },
  "nemSch_e051": {
    "primaryTargetElementId": "eTimes.13",
    "source": "when not(any(undocumented(\"eTimes.13\"), emptyPayload(\"eTimes.13\")))\nrequire any(any(undocumented(\"eTimes.11\"), emptyPayload(\"eTimes.11\")), timeCompare(\"eTimes.13\", \"same-or-after\", \"eTimes.11\"))"
  },
  "nemSch_e052": {
    "primaryTargetElementId": "eTimes.13",
    "source": "when not(any(undocumented(\"eTimes.13\"), emptyPayload(\"eTimes.13\")))\nrequire any(any(undocumented(\"eTimes.12\"), emptyPayload(\"eTimes.12\")), timeCompare(\"eTimes.13\", \"same-or-after\", \"eTimes.12\"))"
  },
  "nemSch_e053": {
    "primaryTargetElementId": "eTimes.13",
    "source": "when not(any(undocumented(\"eTimes.13\"), emptyPayload(\"eTimes.13\")))\nrequire any(any(undocumented(\"eSituation.01\"), emptyPayload(\"eSituation.01\")), timeCompare(\"eTimes.13\", \"same-or-after\", \"eSituation.01\"))"
  },
  "nemSch_e054": {
    "primaryTargetElementId": "eTimes.13",
    "source": "when not(any(undocumented(\"eTimes.13\"), emptyPayload(\"eTimes.13\")))\nrequire any(any(undocumented(\"eSituation.18\"), emptyPayload(\"eSituation.18\")), timeCompare(\"eTimes.13\", \"same-or-after\", \"eSituation.18\"))"
  },
  "nemSch_e055": {
    "primaryTargetElementId": "eTimes.13",
    "source": "when not(any(undocumented(\"eTimes.13\"), emptyPayload(\"eTimes.13\")))\nrequire any(any(undocumented(\"eArrest.14\"), emptyPayload(\"eArrest.14\")), timeCompare(\"eTimes.13\", \"same-or-after\", \"eArrest.14\"))"
  },
  "nemSch_e056": {
    "primaryTargetElementId": "eTimes.13",
    "source": "when not(any(undocumented(\"eTimes.13\"), emptyPayload(\"eTimes.13\")))\nrequire timeCompare(\"eTimes.13\", \"same-or-before\", \"evaluation-time\", 3600)"
  },
  "nemSch_e057": {
    "primaryTargetElementId": "ePatient.07",
    "source": "when any(undocumented(\"ePatient.07\"), emptyPayload(\"ePatient.07\"))\nrequire compareValue(\"eDisposition.28\", \"not-equal\", \"4228001\")"
  },
  "nemSch_e058": {
    "primaryTargetElementId": "ePatient.07",
    "source": "when not(any(undocumented(\"ePatient.07\"), emptyPayload(\"ePatient.07\")))\nrequire startsWith(\"ePatient.07\", \"ePatient.08\")"
  },
  "nemSch_e059": {
    "primaryTargetElementId": "ePatient.08",
    "source": "when any(undocumented(\"ePatient.08\"), emptyPayload(\"ePatient.08\"))\nrequire compareValue(\"eDisposition.28\", \"not-equal\", \"4228001\")"
  },
  "nemSch_e060": {
    "primaryTargetElementId": "ePatient.09",
    "source": "when any(undocumented(\"ePatient.09\"), emptyPayload(\"ePatient.09\"))\nrequire compareValue(\"eDisposition.28\", \"not-equal\", \"4228001\")"
  },
  "nemSch_e062": {
    "primaryTargetElementId": "ePatient.14",
    "source": "when any(undocumented(\"ePatient.14\"), emptyPayload(\"ePatient.14\"))\nrequire any(not(any(undocumented(\"ePatient.14\"), emptyPayload(\"ePatient.14\"))), compareValue(\"eDisposition.28\", \"not-equal\", \"4228001\"))"
  },
  "nemSch_e063": {
    "primaryTargetElementId": "ePatient.15",
    "source": "for each(\"ePatient.AgeGroup\")\nwhen any(undocumented(\"ePatient.15\"), emptyPayload(\"ePatient.15\"))\nrequire compareValue(\"eDisposition.28\", \"not-equal\", \"4228001\")"
  },
  "nemSch_e064": {
    "primaryTargetElementId": "ePatient.16",
    "source": "for each(\"ePatient.AgeGroup\")\nwhen any(undocumented(\"ePatient.16\"), emptyPayload(\"ePatient.16\"))\nrequire compareValue(\"eDisposition.28\", \"not-equal\", \"4228001\")"
  },
  "nemSch_e065": {
    "primaryTargetElementId": "ePatient.16",
    "source": "for each(\"ePatient.AgeGroup\")\nwhen any(undocumented(\"ePatient.16\"), emptyPayload(\"ePatient.16\"))\nrequire any(undocumented(\"ePatient.15\"), emptyPayload(\"ePatient.15\"))"
  },
  "nemSch_e193": {
    "primaryTargetElementId": "ePatient.25",
    "source": "when not(not(any(undocumented(\"ePatient.25\"), emptyPayload(\"ePatient.25\"))))\nrequire compareValue(\"eDisposition.28\", \"not-equal\", \"4228001\")"
  },
  "nemSch_e067": {
    "primaryTargetElementId": "eScene.06",
    "source": "require any(member(\"eScene.06\", \"2707001\", \"2707005\"), compareValue(\"eDisposition.27\", \"not-equal\", \"4227001\"))"
  },
  "nemSch_e068": {
    "primaryTargetElementId": "eScene.06",
    "source": "require any(compareValue(\"eScene.06\", \"equal\", \"2707001\"), compareValue(\"eScene.07\", \"not-equal\", \"9923003\"))"
  },
  "nemSch_e069": {
    "primaryTargetElementId": "eScene.08",
    "source": "when any(undocumented(\"eScene.08\"), emptyPayload(\"eScene.08\"))\nrequire compareValue(\"eScene.07\", \"not-equal\", \"9923003\")"
  },
  "nemSch_e070": {
    "primaryTargetElementId": "eScene.09",
    "source": "when any(undocumented(\"eScene.09\"), emptyPayload(\"eScene.09\"))\nrequire compareValue(\"eDisposition.27\", \"equal\", \"4227005\")"
  },
  "nemSch_e071": {
    "primaryTargetElementId": "eScene.18",
    "source": "when any(undocumented(\"eScene.18\"), emptyPayload(\"eScene.18\"))\nrequire compareValue(\"eDisposition.27\", \"equal\", \"4227005\")"
  },
  "nemSch_e072": {
    "primaryTargetElementId": "eScene.19",
    "source": "when any(undocumented(\"eScene.19\"), emptyPayload(\"eScene.19\"))\nrequire compareValue(\"eDisposition.27\", \"equal\", \"4227005\")"
  },
  "nemSch_e073": {
    "primaryTargetElementId": "eScene.21",
    "source": "when any(undocumented(\"eScene.21\"), emptyPayload(\"eScene.21\"))\nrequire compareValue(\"eDisposition.27\", \"equal\", \"4227005\")"
  },
  "nemSch_e074": {
    "primaryTargetElementId": "eScene.21",
    "source": "when not(any(undocumented(\"eScene.21\"), emptyPayload(\"eScene.21\")))\nrequire startsWith(\"eScene.21\", \"eScene.18\")"
  },
  "nemSch_e075": {
    "primaryTargetElementId": "eSituation.01",
    "source": "when any(undocumented(\"eSituation.01\"), emptyPayload(\"eSituation.01\"))\nrequire any(compareValue(\"eResponse.05\", \"not-equal\", \"2205001\"), compareValue(\"eDisposition.28\", \"not-equal\", \"4228001\"))"
  },
  "nemSch_e076": {
    "primaryTargetElementId": "eSituation.02",
    "source": "require any(not(any(undocumented(\"eSituation.02\"), emptyPayload(\"eSituation.02\"))), compareValue(\"eResponse.05\", \"not-equal\", \"2205001\"), compareValue(\"eDisposition.28\", \"not-equal\", \"4228001\"))"
  },
  "nemSch_e077": {
    "primaryTargetElementId": "eSituation.02",
    "source": "require any(compareValue(\"eSituation.02\", \"equal\", \"9922005\"), not(any(matches(\"eSituation.09\", \"^(S|T(0\\\\d|1[0-4]))\"), matches(\"eSituation.10\", \"^(S|T(0\\\\d|1[0-4]))\"), matches(\"eSituation.11\", \"^(S|T(0\\\\d|1[0-4]))\"), matches(\"eSituation.12\", \"^(S|T(0\\\\d|1[0-4]))\"))))"
  },
  "nemSch_e080": {
    "primaryTargetElementId": "eSituation.09",
    "source": "when any(undocumented(\"eSituation.09\"), emptyPayload(\"eSituation.09\"))\nrequire any(compareValue(\"eResponse.05\", \"not-equal\", \"2205001\"), compareValue(\"eDisposition.28\", \"not-equal\", \"4228001\"))"
  },
  "nemSch_e081": {
    "primaryTargetElementId": "eSituation.10",
    "source": "when not(any(undocumented(\"eSituation.10\"), emptyPayload(\"eSituation.10\")))\nrequire not(any(undocumented(\"eSituation.09\"), emptyPayload(\"eSituation.09\")))"
  },
  "nemSch_e082": {
    "primaryTargetElementId": "eSituation.11",
    "source": "when any(undocumented(\"eSituation.11\"), emptyPayload(\"eSituation.11\"))\nrequire any(compareValue(\"eResponse.05\", \"not-equal\", \"2205001\"), compareValue(\"eDisposition.28\", \"not-equal\", \"4228001\"))"
  },
  "nemSch_e083": {
    "primaryTargetElementId": "eSituation.12",
    "source": "when not(any(undocumented(\"eSituation.12\"), emptyPayload(\"eSituation.12\")))\nrequire not(any(undocumented(\"eSituation.11\"), emptyPayload(\"eSituation.11\")))"
  },
  "nemSch_e084": {
    "primaryTargetElementId": "eSituation.13",
    "source": "when any(undocumented(\"eSituation.13\"), emptyPayload(\"eSituation.13\"))\nrequire any(compareValue(\"eResponse.05\", \"not-equal\", \"2205001\"), compareValue(\"eDisposition.28\", \"not-equal\", \"4228001\"))"
  },
  "nemSch_e085": {
    "primaryTargetElementId": "eSituation.18",
    "source": "when any(undocumented(\"eSituation.18\"), emptyPayload(\"eSituation.18\"))\nrequire any(compareValue(\"eDisposition.28\", \"not-equal\", \"4228001\"), not(member(\"eArrest.01\", \"3001003\", \"3001005\")))"
  },
  "nemSch_e086": {
    "primaryTargetElementId": "eSituation.18",
    "source": "when any(undocumented(\"eSituation.18\"), emptyPayload(\"eSituation.18\"))\nrequire any(compareValue(\"eDisposition.28\", \"not-equal\", \"4228001\"), not(compareValue(\"eVitals.29\", \"equal\", \"3329005\")))"
  },
  "nemSch_e087": {
    "primaryTargetElementId": "eSituation.18",
    "source": "when any(undocumented(\"eSituation.18\"), emptyPayload(\"eSituation.18\"))\nrequire any(compareValue(\"eDisposition.28\", \"not-equal\", \"4228001\"), not(member(\"eVitals.03\", \"9901051\", \"9901053\", \"9901055\", \"9901057\", \"9901058\")))"
  },
  "nemSch_e088": {
    "primaryTargetElementId": "eSituation.20",
    "source": "when not(any(undocumented(\"eSituation.20\"), emptyPayload(\"eSituation.20\")))\nrequire member(\"eResponse.05\", \"2205005\", \"2205007\", \"2205015\", \"2205017\", \"2205019\")"
  },
  "nemSch_e089": {
    "primaryTargetElementId": "eInjury.01",
    "source": "when any(undocumented(\"eInjury.01\"), emptyPayload(\"eInjury.01\"))\nrequire any(not(any(undocumented(\"eInjury.01\"), emptyPayload(\"eInjury.01\"))), compareValue(\"eSituation.02\", \"not-equal\", \"9922005\"), compareValue(\"eDisposition.28\", \"not-equal\", \"4228001\"))"
  },
  "nemSch_e090": {
    "primaryTargetElementId": "eInjury.01",
    "source": "when not(any(undocumented(\"eInjury.01\"), emptyPayload(\"eInjury.01\")))\nrequire compareValue(\"eSituation.02\", \"equal\", \"9922005\")"
  },
  "nemSch_e091": {
    "primaryTargetElementId": "eInjury.03",
    "source": "when not(any(undocumented(\"eInjury.03\"), emptyPayload(\"eInjury.03\")))\nrequire compareValue(\"eSituation.02\", \"equal\", \"9922005\")"
  },
  "nemSch_e092": {
    "primaryTargetElementId": "eInjury.04",
    "source": "when not(any(undocumented(\"eInjury.04\"), emptyPayload(\"eInjury.04\")))\nrequire compareValue(\"eSituation.02\", \"equal\", \"9922005\")"
  },
  "nemSch_e093": {
    "primaryTargetElementId": "eArrest.02",
    "source": "when any(undocumented(\"eArrest.02\"), emptyPayload(\"eArrest.02\"))\nrequire any(not(member(\"eArrest.01\", \"3001003\", \"3001005\")), compareValue(\"eDisposition.28\", \"not-equal\", \"4228001\"))"
  },
  "nemSch_e094": {
    "primaryTargetElementId": "eArrest.02",
    "source": "when not(any(undocumented(\"eArrest.02\"), emptyPayload(\"eArrest.02\")))\nrequire member(\"eArrest.01\", \"3001003\", \"3001005\")"
  },
  "nemSch_e095": {
    "primaryTargetElementId": "eArrest.03",
    "source": "require any(not(any(undocumented(\"eArrest.03\"), emptyPayload(\"eArrest.03\"))), not(member(\"eArrest.01\", \"3001003\", \"3001005\")), compareValue(\"eDisposition.28\", \"not-equal\", \"4228001\"))"
  },
  "nemSch_e096": {
    "primaryTargetElementId": "eArrest.03",
    "source": "require any(not(not(any(undocumented(\"eArrest.03\"), emptyPayload(\"eArrest.03\")))), member(\"eArrest.01\", \"3001003\", \"3001005\"))"
  },
  "nemSch_e097": {
    "primaryTargetElementId": "eArrest.03",
    "source": "require not(all(member(\"eArrest.03\", \"3003001\", \"3003003\", \"3003005\"), member(\"eArrest.03\", \"3003007\", \"3003009\", \"3003011\")))"
  },
  "nemSch_e098": {
    "primaryTargetElementId": "eArrest.03",
    "source": "require any(compareValue(\"eArrest.03\", \"equal\", \"3003005\"), not(member(\"eArrest.09\", \"3009001\", \"3009003\", \"3009005\", \"3009007\", \"3009009\", \"3009011\", \"3009021\")))"
  },
  "nemSch_e099": {
    "primaryTargetElementId": "eArrest.03",
    "source": "require any(compareValue(\"eArrest.03\", \"equal\", \"3003003\"), not(member(\"eArrest.09\", \"3009009\", \"3009013\", \"3009015\", \"3009017\", \"3009019\", \"3009023\", \"3009025\", \"3009027\")))"
  },
  "nemSch_e100": {
    "primaryTargetElementId": "eArrest.04",
    "source": "when any(undocumented(\"eArrest.04\"), emptyPayload(\"eArrest.04\"))\nrequire any(not(any(undocumented(\"eArrest.04\"), emptyPayload(\"eArrest.04\"))), not(member(\"eArrest.01\", \"3001003\", \"3001005\")), compareValue(\"eDisposition.28\", \"not-equal\", \"4228001\"))"
  },
  "nemSch_e101": {
    "primaryTargetElementId": "eArrest.04",
    "source": "when not(any(undocumented(\"eArrest.04\"), emptyPayload(\"eArrest.04\")))\nrequire member(\"eArrest.01\", \"3001003\", \"3001005\")"
  },
  "nemSch_e102": {
    "primaryTargetElementId": "eArrest.04",
    "source": "when not(any(undocumented(\"eArrest.04\"), emptyPayload(\"eArrest.04\")))\nrequire any(not(compareValue(\"eArrest.04\", \"equal\", \"3004001\")), all(minimum(\"eArrest.04\", 1), maximum(\"eArrest.04\", 1)))"
  },
  "nemSch_e103": {
    "primaryTargetElementId": "eArrest.07",
    "source": "when any(undocumented(\"eArrest.07\"), emptyPayload(\"eArrest.07\"))\nrequire any(not(compareValue(\"eArrest.01\", \"equal\", \"3001003\")), compareValue(\"eDisposition.28\", \"not-equal\", \"4228001\"))"
  },
  "nemSch_e104": {
    "primaryTargetElementId": "eArrest.07",
    "source": "when not(any(undocumented(\"eArrest.07\"), emptyPayload(\"eArrest.07\")))\nrequire member(\"eArrest.01\", \"3001003\", \"3001005\")"
  },
  "nemSch_e105": {
    "primaryTargetElementId": "eArrest.09",
    "source": "require any(not(not(any(undocumented(\"eArrest.09\"), emptyPayload(\"eArrest.09\")))), member(\"eArrest.01\", \"3001003\", \"3001005\"))"
  },
  "nemSch_e106": {
    "primaryTargetElementId": "eArrest.09",
    "source": "require any(not(compareValue(\"eArrest.03\", \"equal\", \"3003005\")), member(\"eArrest.09\", \"3009001\", \"3009003\", \"3009005\", \"3009007\", \"3009009\", \"3009011\", \"3009021\"))"
  },
  "nemSch_e107": {
    "primaryTargetElementId": "eArrest.09",
    "source": "require any(not(compareValue(\"eArrest.03\", \"equal\", \"3003003\")), member(\"eArrest.09\", \"3009009\", \"3009013\", \"3009015\", \"3009017\", \"3009019\", \"3009023\", \"3009025\", \"3009027\"))"
  },
  "nemSch_e108": {
    "primaryTargetElementId": "eArrest.12",
    "source": "when any(undocumented(\"eArrest.12\"), emptyPayload(\"eArrest.12\"))\nrequire any(not(any(undocumented(\"eArrest.12\"), emptyPayload(\"eArrest.12\"))), not(member(\"eArrest.01\", \"3001003\", \"3001005\")), compareValue(\"eDisposition.28\", \"not-equal\", \"4228001\"))"
  },
  "nemSch_e109": {
    "primaryTargetElementId": "eArrest.12",
    "source": "when not(any(undocumented(\"eArrest.12\"), emptyPayload(\"eArrest.12\")))\nrequire member(\"eArrest.01\", \"3001003\", \"3001005\")"
  },
  "nemSch_e110": {
    "primaryTargetElementId": "eArrest.12",
    "source": "when not(any(undocumented(\"eArrest.12\"), emptyPayload(\"eArrest.12\")))\nrequire any(not(compareValue(\"eArrest.12\", \"equal\", \"3012001\")), all(minimum(\"eArrest.12\", 1), maximum(\"eArrest.12\", 1)))"
  },
  "nemSch_e111": {
    "primaryTargetElementId": "eArrest.14",
    "source": "when not(any(undocumented(\"eArrest.14\"), emptyPayload(\"eArrest.14\")))\nrequire member(\"eArrest.01\", \"3001003\", \"3001005\")"
  },
  "nemSch_e112": {
    "primaryTargetElementId": "eArrest.16",
    "source": "when not(any(undocumented(\"eArrest.16\"), emptyPayload(\"eArrest.16\")))\nrequire member(\"eArrest.01\", \"3001003\", \"3001005\")"
  },
  "nemSch_e113": {
    "primaryTargetElementId": "eArrest.17",
    "source": "when any(undocumented(\"eArrest.17\"), emptyPayload(\"eArrest.17\"))\nrequire any(not(any(undocumented(\"eArrest.17\"), emptyPayload(\"eArrest.17\"))), not(member(\"eArrest.01\", \"3001003\", \"3001005\")), not(member(\"eDisposition.30\", \"4230001\", \"4230001\")))"
  },
  "nemSch_e114": {
    "primaryTargetElementId": "eArrest.17",
    "source": "when not(any(undocumented(\"eArrest.17\"), emptyPayload(\"eArrest.17\")))\nrequire member(\"eArrest.01\", \"3001003\", \"3001005\")"
  },
  "nemSch_e115": {
    "primaryTargetElementId": "eArrest.18",
    "source": "when any(undocumented(\"eArrest.18\"), emptyPayload(\"eArrest.18\"))\nrequire any(not(member(\"eArrest.01\", \"3001003\", \"3001005\")), compareValue(\"eDisposition.28\", \"not-equal\", \"4228001\"))"
  },
  "nemSch_e116": {
    "primaryTargetElementId": "eArrest.18",
    "source": "when not(any(undocumented(\"eArrest.18\"), emptyPayload(\"eArrest.18\")))\nrequire member(\"eArrest.01\", \"3001003\", \"3001005\")"
  },
  "nemSch_e117": {
    "primaryTargetElementId": "eArrest.20",
    "source": "when any(undocumented(\"eArrest.20\"), emptyPayload(\"eArrest.20\"))\nrequire not(member(\"eArrest.03\", \"3003001\", \"3003003\", \"3003005\"))"
  },
  "nemSch_e118": {
    "primaryTargetElementId": "eArrest.20",
    "source": "when not(any(undocumented(\"eArrest.20\"), emptyPayload(\"eArrest.20\")))\nrequire member(\"eArrest.01\", \"3001003\", \"3001005\")"
  },
  "nemSch_e119": {
    "primaryTargetElementId": "eArrest.21",
    "source": "when any(undocumented(\"eArrest.21\"), emptyPayload(\"eArrest.21\"))\nrequire not(member(\"eArrest.07\", \"3007003\", \"3007005\"))"
  },
  "nemSch_e120": {
    "primaryTargetElementId": "eArrest.21",
    "source": "when not(any(undocumented(\"eArrest.21\"), emptyPayload(\"eArrest.21\")))\nrequire member(\"eArrest.01\", \"3001003\", \"3001005\")"
  },
  "nemSch_e122": {
    "primaryTargetElementId": "eArrest.22",
    "source": "when any(undocumented(\"eArrest.22\"), emptyPayload(\"eArrest.22\"))\nrequire not(compareValue(\"eArrest.07\", \"equal\", \"3007005\"))"
  },
  "nemSch_e123": {
    "primaryTargetElementId": "eArrest.22",
    "source": "when not(any(undocumented(\"eArrest.22\"), emptyPayload(\"eArrest.22\")))\nrequire member(\"eArrest.01\", \"3001003\", \"3001005\")"
  },
  "nemSch_e124": {
    "primaryTargetElementId": "eHistory.01",
    "source": "when compareValue(\"eHistory.01\", \"equal\", \"3101009\")\nrequire all(minimum(\"eHistory.01\", 1), maximum(\"eHistory.01\", 1))"
  },
  "nemSch_e125": {
    "primaryTargetElementId": "eVitals.01",
    "source": "for each(\"eVitals.VitalGroup\")\nwhen all(anyPayload(), any(undocumented(\"eVitals.01\"), emptyPayload(\"eVitals.01\")))\nrequire compareValue(\"eVitals.02\", \"equal\", \"9923003\")"
  },
  "nemSch_e126": {
    "primaryTargetElementId": "eVitals.01",
    "source": "for each(\"eVitals.VitalGroup\")\nwhen not(any(undocumented(\"eVitals.01\"), emptyPayload(\"eVitals.01\")))\nrequire any(timeCompare(\"eVitals.01\", \"same-or-after\", \"eTimes.03\"), compareValue(\"eVitals.02\", \"equal\", \"9923003\"))"
  },
  "nemSch_e127": {
    "primaryTargetElementId": "eVitals.01",
    "source": "for each(\"eVitals.VitalGroup\")\nwhen not(any(undocumented(\"eVitals.01\"), emptyPayload(\"eVitals.01\")))\nrequire any(any(undocumented(\"eTimes.07\"), emptyPayload(\"eTimes.07\")), timeCompare(\"eVitals.01\", \"same-or-after\", \"eTimes.07\"), compareValue(\"eVitals.02\", \"equal\", \"9923003\"))"
  },
  "nemSch_e128": {
    "primaryTargetElementId": "eVitals.01",
    "source": "for each(\"eVitals.VitalGroup\")\nwhen not(any(undocumented(\"eVitals.01\"), emptyPayload(\"eVitals.01\")))\nrequire any(any(undocumented(\"eTimes.12\"), emptyPayload(\"eTimes.12\")), timeCompare(\"eVitals.01\", \"same-or-before\", \"eTimes.12\"))"
  },
  "nemSch_e129": {
    "primaryTargetElementId": "eVitals.01",
    "source": "for each(\"eVitals.VitalGroup\")\nwhen not(any(undocumented(\"eVitals.01\"), emptyPayload(\"eVitals.01\")))\nrequire timeCompare(\"eVitals.01\", \"same-or-before\", \"eTimes.13\")"
  },
  "nemSch_e130": {
    "primaryTargetElementId": "eVitals.01",
    "source": "for each(\"eVitals.VitalGroup\")\nwhen not(any(undocumented(\"eVitals.01\"), emptyPayload(\"eVitals.01\")))\nrequire any(any(undocumented(\"eTimes.07\"), emptyPayload(\"eTimes.07\")), timeCompare(\"eVitals.01\", \"same-or-before\", \"eTimes.07\"), compareValue(\"eVitals.02\", \"not-equal\", \"9923003\"))"
  },
  "nemSch_e131": {
    "primaryTargetElementId": "eVitals.16",
    "source": "for each(\"eVitals.VitalGroup\")\nwhen not(any(undocumented(\"eVitals.16\"), emptyPayload(\"eVitals.16\")))\nrequire any(compareValue(\"eVitals.16\", \"less-or-equal\", 100), not(attribute(\"eVitals.16\", \"ETCO2Type\", \"3340003\")))"
  },
  "nemSch_e132": {
    "primaryTargetElementId": "eVitals.16",
    "source": "for each(\"eVitals.VitalGroup\")\nwhen not(any(undocumented(\"eVitals.16\"), emptyPayload(\"eVitals.16\")))\nrequire any(compareValue(\"eVitals.16\", \"less-or-equal\", 100), not(attribute(\"eVitals.16\", \"ETCO2Type\", \"3340005\")))"
  },
  "nemSch_e133": {
    "primaryTargetElementId": "eVitals.16",
    "source": "for each(\"eVitals.VitalGroup\")\nwhen not(any(undocumented(\"eVitals.16\"), emptyPayload(\"eVitals.16\")))\nrequire any(matches(\"eVitals.16\", \"^-?[0-9]+$\"), not(attribute(\"eVitals.16\", \"ETCO2Type\", \"3340001\")))"
  },
  "nemSch_e134": {
    "primaryTargetElementId": "eVitals.16",
    "source": "for each(\"eVitals.VitalGroup\")\nwhen not(any(undocumented(\"eVitals.16\"), emptyPayload(\"eVitals.16\")))\nrequire attribute(\"eVitals.16\", \"ETCO2Type\")"
  },
  "nemSch_e135": {
    "primaryTargetElementId": "eVitals.22",
    "source": "for each(\"eVitals.VitalGroup\")\nwhen compareValue(\"eVitals.22\", \"equal\", \"3322003\")\nrequire all(minimum(\"eVitals.22\", 1), maximum(\"eVitals.22\", 1))"
  },
  "nemSch_e136": {
    "primaryTargetElementId": "eMedications.01",
    "source": "for each(\"eMedications.MedicationGroup\")\nwhen all(anyPayload(), any(undocumented(\"eMedications.01\"), emptyPayload(\"eMedications.01\")))\nrequire compareValue(\"eMedications.02\", \"equal\", \"9923003\")"
  },
  "nemSch_e137": {
    "primaryTargetElementId": "eMedications.01",
    "source": "for each(\"eMedications.MedicationGroup\")\nwhen not(any(undocumented(\"eMedications.01\"), emptyPayload(\"eMedications.01\")))\nrequire any(timeCompare(\"eMedications.01\", \"same-or-after\", \"eTimes.03\"), compareValue(\"eMedications.02\", \"equal\", \"9923003\"))"
  },
  "nemSch_e138": {
    "primaryTargetElementId": "eMedications.01",
    "source": "for each(\"eMedications.MedicationGroup\")\nwhen not(any(undocumented(\"eMedications.01\"), emptyPayload(\"eMedications.01\")))\nrequire any(any(undocumented(\"eTimes.07\"), emptyPayload(\"eTimes.07\")), timeCompare(\"eMedications.01\", \"same-or-after\", \"eTimes.07\"), compareValue(\"eMedications.02\", \"equal\", \"9923003\"))"
  },
  "nemSch_e139": {
    "primaryTargetElementId": "eMedications.01",
    "source": "for each(\"eMedications.MedicationGroup\")\nwhen not(any(undocumented(\"eMedications.01\"), emptyPayload(\"eMedications.01\")))\nrequire any(any(undocumented(\"eTimes.12\"), emptyPayload(\"eTimes.12\")), timeCompare(\"eMedications.01\", \"same-or-before\", \"eTimes.12\"))"
  },
  "nemSch_e140": {
    "primaryTargetElementId": "eMedications.01",
    "source": "for each(\"eMedications.MedicationGroup\")\nwhen not(any(undocumented(\"eMedications.01\"), emptyPayload(\"eMedications.01\")))\nrequire timeCompare(\"eMedications.01\", \"same-or-before\", \"eTimes.13\")"
  },
  "nemSch_e141": {
    "primaryTargetElementId": "eMedications.01",
    "source": "for each(\"eMedications.MedicationGroup\")\nwhen not(any(undocumented(\"eMedications.01\"), emptyPayload(\"eMedications.01\")))\nrequire any(any(undocumented(\"eTimes.07\"), emptyPayload(\"eTimes.07\")), timeCompare(\"eMedications.01\", \"same-or-before\", \"eTimes.07\"), compareValue(\"eMedications.02\", \"not-equal\", \"9923003\"))"
  },
  "nemSch_e142": {
    "primaryTargetElementId": "eMedications.03",
    "source": "for each(\"eMedications.MedicationGroup\")\nwhen all(anyPayload(), any(undocumented(\"eMedications.03\"), emptyPayload(\"eMedications.03\")))\nrequire never()"
  },
  "nemSch_e143": {
    "primaryTargetElementId": "eMedications.03",
    "source": "for each(\"eMedications.MedicationGroup\")\nwhen all(not(any(undocumented(\"eMedications.03\"), emptyPayload(\"eMedications.03\"))), attribute(\"eMedications.03\", \"CodeType\"))\nrequire any(matches(\"eMedications.03\", \"^[0-9]{2,7}$\"), not(codeType(\"eMedications.03\", \"9924003\")))"
  },
  "nemSch_e144": {
    "primaryTargetElementId": "eMedications.03",
    "source": "for each(\"eMedications.MedicationGroup\")\nwhen all(not(any(undocumented(\"eMedications.03\"), emptyPayload(\"eMedications.03\"))), attribute(\"eMedications.03\", \"CodeType\"))\nrequire any(member(\"eMedications.03\", \"116762002\", \"116795008\", \"116861002\", \"116865006\", \"180208003\", \"33389009\", \"71493000\"), not(codeType(\"eMedications.03\", \"9924005\")))"
  },
  "nemSch_e145": {
    "primaryTargetElementId": "eMedications.03",
    "source": "for each(\"eMedications.MedicationGroup\")\nwhen all(not(any(undocumented(\"eMedications.03\"), emptyPayload(\"eMedications.03\"))), not(attribute(\"eMedications.03\", \"CodeType\")))\nrequire any(matches(\"eMedications.03\", \"^[0-9]{2,7}$\"), member(\"eMedications.03\", \"116762002\", \"116795008\", \"116861002\", \"116865006\", \"180208003\", \"33389009\", \"71493000\"))"
  },
  "nemSch_e146": {
    "primaryTargetElementId": "eMedications.04",
    "source": "for each(\"eMedications.MedicationGroup\")\nwhen all(anyPayload(), any(undocumented(\"eMedications.04\"), emptyPayload(\"eMedications.04\")))\nrequire compareValue(\"eMedications.02\", \"equal\", \"9923003\")"
  },
  "nemSch_e147": {
    "primaryTargetElementId": "eMedications.05",
    "source": "for each(\"eMedications.DosageGroup\")\nwhen all(anyPayload(), any(undocumented(\"eMedications.05\"), emptyPayload(\"eMedications.05\")))\nrequire compareValue(\"eMedications.02\", \"equal\", \"9923003\")"
  },
  "nemSch_e148": {
    "primaryTargetElementId": "eMedications.06",
    "source": "for each(\"eMedications.DosageGroup\")\nwhen all(anyPayload(), any(undocumented(\"eMedications.06\"), emptyPayload(\"eMedications.06\")))\nrequire compareValue(\"eMedications.02\", \"equal\", \"9923003\")"
  },
  "nemSch_e149": {
    "primaryTargetElementId": "eMedications.08",
    "source": "for each(\"eMedications.MedicationGroup\")\nwhen compareValue(\"eMedications.08\", \"equal\", \"3708031\")\nrequire all(minimum(\"eMedications.08\", 1), maximum(\"eMedications.08\", 1))"
  },
  "nemSch_e150": {
    "primaryTargetElementId": "eMedications.10",
    "source": "for each(\"eMedications.MedicationGroup\")\nwhen all(anyPayload(), any(undocumented(\"eMedications.10\"), emptyPayload(\"eMedications.10\")))\nrequire compareValue(\"eMedications.02\", \"equal\", \"9923003\")"
  },
  "nemSch_e151": {
    "primaryTargetElementId": "eProcedures.01",
    "source": "for each(\"eProcedures.ProcedureGroup\")\nwhen all(anyPayload(), any(undocumented(\"eProcedures.01\"), emptyPayload(\"eProcedures.01\")))\nrequire compareValue(\"eProcedures.02\", \"equal\", \"9923003\")"
  },
  "nemSch_e152": {
    "primaryTargetElementId": "eProcedures.01",
    "source": "for each(\"eProcedures.ProcedureGroup\")\nwhen not(any(undocumented(\"eProcedures.01\"), emptyPayload(\"eProcedures.01\")))\nrequire any(timeCompare(\"eProcedures.01\", \"same-or-after\", \"eTimes.03\"), compareValue(\"eProcedures.02\", \"equal\", \"9923003\"))"
  },
  "nemSch_e153": {
    "primaryTargetElementId": "eProcedures.01",
    "source": "for each(\"eProcedures.ProcedureGroup\")\nwhen not(any(undocumented(\"eProcedures.01\"), emptyPayload(\"eProcedures.01\")))\nrequire any(any(undocumented(\"eTimes.07\"), emptyPayload(\"eTimes.07\")), timeCompare(\"eProcedures.01\", \"same-or-after\", \"eTimes.07\"), compareValue(\"eProcedures.02\", \"equal\", \"9923003\"))"
  },
  "nemSch_e154": {
    "primaryTargetElementId": "eProcedures.01",
    "source": "for each(\"eProcedures.ProcedureGroup\")\nwhen not(any(undocumented(\"eProcedures.01\"), emptyPayload(\"eProcedures.01\")))\nrequire any(any(undocumented(\"eTimes.12\"), emptyPayload(\"eTimes.12\")), timeCompare(\"eProcedures.01\", \"same-or-before\", \"eTimes.12\"))"
  },
  "nemSch_e155": {
    "primaryTargetElementId": "eProcedures.01",
    "source": "for each(\"eProcedures.ProcedureGroup\")\nwhen not(any(undocumented(\"eProcedures.01\"), emptyPayload(\"eProcedures.01\")))\nrequire timeCompare(\"eProcedures.01\", \"same-or-before\", \"eTimes.13\")"
  },
  "nemSch_e156": {
    "primaryTargetElementId": "eProcedures.01",
    "source": "for each(\"eProcedures.ProcedureGroup\")\nwhen not(any(undocumented(\"eProcedures.01\"), emptyPayload(\"eProcedures.01\")))\nrequire any(any(undocumented(\"eTimes.07\"), emptyPayload(\"eTimes.07\")), timeCompare(\"eProcedures.01\", \"same-or-before\", \"eTimes.07\"), compareValue(\"eProcedures.02\", \"not-equal\", \"9923003\"))"
  },
  "nemSch_e157": {
    "primaryTargetElementId": "eProcedures.03",
    "source": "for each(\"eProcedures.ProcedureGroup\")\nwhen all(anyPayload(), any(undocumented(\"eProcedures.03\"), emptyPayload(\"eProcedures.03\")))\nrequire never()"
  },
  "nemSch_e158": {
    "primaryTargetElementId": "eProcedures.07",
    "source": "for each(\"eProcedures.ProcedureGroup\")\nwhen compareValue(\"eProcedures.07\", \"equal\", \"3907033\")\nrequire all(minimum(\"eProcedures.07\", 1), maximum(\"eProcedures.07\", 1))"
  },
  "nemSch_e159": {
    "primaryTargetElementId": "eProcedures.10",
    "source": "for each(\"eProcedures.ProcedureGroup\")\nwhen all(anyPayload(), any(undocumented(\"eProcedures.10\"), emptyPayload(\"eProcedures.10\")))\nrequire compareValue(\"eProcedures.02\", \"equal\", \"9923003\")"
  },
  "nemSch_e160": {
    "primaryTargetElementId": "eDisposition.05",
    "source": "for each(\"eDisposition.DestinationGroup\")\nwhen any(undocumented(\"eDisposition.05\"), emptyPayload(\"eDisposition.05\"))\nrequire not(member(\"eDisposition.30\", \"4230001\", \"4230003\"))"
  },
  "nemSch_e161": {
    "primaryTargetElementId": "eDisposition.06",
    "source": "for each(\"eDisposition.DestinationGroup\")\nwhen any(undocumented(\"eDisposition.06\"), emptyPayload(\"eDisposition.06\"))\nrequire not(member(\"eDisposition.30\", \"4230001\", \"4230003\"))"
  },
  "nemSch_e162": {
    "primaryTargetElementId": "eDisposition.06",
    "source": "for each(\"eDisposition.DestinationGroup\")\nwhen not(any(undocumented(\"eDisposition.06\"), emptyPayload(\"eDisposition.06\")))\nrequire startsWith(\"eDisposition.06\", \"eDisposition.05\")"
  },
  "nemSch_e163": {
    "primaryTargetElementId": "eDisposition.07",
    "source": "for each(\"eDisposition.DestinationGroup\")\nwhen any(undocumented(\"eDisposition.07\"), emptyPayload(\"eDisposition.07\"))\nrequire not(member(\"eDisposition.30\", \"4230001\", \"4230003\"))"
  },
  "nemSch_e164": {
    "primaryTargetElementId": "eDisposition.16",
    "source": "require any(not(any(undocumented(\"eDisposition.16\"), emptyPayload(\"eDisposition.16\"))), not(member(\"eDisposition.30\", \"4230001\", \"4230003\")))"
  },
  "nemSch_e165": {
    "primaryTargetElementId": "eDisposition.16",
    "source": "require any(any(undocumented(\"eDisposition.16\"), emptyPayload(\"eDisposition.16\")), not(member(\"eDisposition.30\", \"4230009\", \"4230013\")))"
  },
  "nemSch_e166": {
    "primaryTargetElementId": "eDisposition.17",
    "source": "require any(not(any(undocumented(\"eDisposition.17\"), emptyPayload(\"eDisposition.17\"))), not(member(\"eDisposition.30\", \"4230001\", \"4230003\")))"
  },
  "nemSch_e167": {
    "primaryTargetElementId": "eDisposition.17",
    "source": "require any(any(undocumented(\"eDisposition.17\"), emptyPayload(\"eDisposition.17\")), not(member(\"eDisposition.30\", \"4230009\", \"4230013\")))"
  },
  "nemSch_e168": {
    "primaryTargetElementId": "eDisposition.19",
    "source": "when any(undocumented(\"eDisposition.19\"), emptyPayload(\"eDisposition.19\"))\nrequire compareValue(\"eDisposition.28\", \"not-equal\", \"4228001\")"
  },
  "nemSch_e169": {
    "primaryTargetElementId": "eDisposition.20",
    "source": "when any(undocumented(\"eDisposition.20\"), emptyPayload(\"eDisposition.20\"))\nrequire any(not(any(undocumented(\"eDisposition.20\"), emptyPayload(\"eDisposition.20\"))), not(member(\"eDisposition.30\", \"4230001\", \"4230003\")))"
  },
  "nemSch_e170": {
    "primaryTargetElementId": "eDisposition.21",
    "source": "when any(undocumented(\"eDisposition.21\"), emptyPayload(\"eDisposition.21\"))\nrequire not(member(\"eDisposition.30\", \"4230001\", \"4230003\"))"
  },
  "nemSch_e171": {
    "primaryTargetElementId": "eDisposition.23",
    "source": "when any(undocumented(\"eDisposition.23\"), emptyPayload(\"eDisposition.23\"))\nrequire any(not(any(undocumented(\"eDisposition.23\"), emptyPayload(\"eDisposition.23\"))), not(all(member(\"eDisposition.21\", \"4221003\", \"4221005\", \"4221023\"), member(\"eArrest.01\", \"3001003\", \"3001005\"))))"
  },
  "nemSch_e172": {
    "primaryTargetElementId": "eDisposition.23",
    "source": "when any(undocumented(\"eDisposition.23\"), emptyPayload(\"eDisposition.23\"))\nrequire any(not(any(undocumented(\"eDisposition.23\"), emptyPayload(\"eDisposition.23\"))), not(all(member(\"eDisposition.21\", \"4221003\", \"4221005\", \"4221023\"), compareValue(\"eVitals.29\", \"equal\", \"3329005\"))))"
  },
  "nemSch_e173": {
    "primaryTargetElementId": "eDisposition.23",
    "source": "when any(undocumented(\"eDisposition.23\"), emptyPayload(\"eDisposition.23\"))\nrequire any(not(any(undocumented(\"eDisposition.23\"), emptyPayload(\"eDisposition.23\"))), not(all(member(\"eDisposition.21\", \"4221003\", \"4221005\", \"4221023\"), member(\"eVitals.03\", \"9901051\", \"9901053\", \"9901055\", \"9901057\", \"9901058\"))))"
  },
  "nemSch_e174": {
    "primaryTargetElementId": "eDisposition.24",
    "source": "when compareValue(\"eDisposition.24\", \"equal\", \"4224001\")\nrequire all(minimum(\"eDisposition.24\", 1), maximum(\"eDisposition.24\", 1))"
  },
  "nemSch_e175": {
    "primaryTargetElementId": "eDisposition.24",
    "source": "for each(\"eDisposition.HospitalTeamActivationGroup\")\nwhen anyPayload()\nrequire not(any(undocumented(\"eDisposition.24\"), emptyPayload(\"eDisposition.24\")))"
  },
  "nemSch_e176": {
    "primaryTargetElementId": "eDisposition.24",
    "source": "for each(\"eDisposition.HospitalTeamActivationGroup\")\nwhen anyPayload()\nrequire any(not(any(undocumented(\"eDisposition.25\"), emptyPayload(\"eDisposition.25\"))), compareValue(\"eDisposition.24\", \"equal\", \"4224001\"))"
  },
  "nemSch_e177": {
    "primaryTargetElementId": "eDisposition.25",
    "source": "for each(\"eDisposition.HospitalTeamActivationGroup\")\nwhen not(any(undocumented(\"eDisposition.25\"), emptyPayload(\"eDisposition.25\")))\nrequire timeCompare(\"eDisposition.25\", \"same-or-after\", \"eTimes.03\")"
  },
  "nemSch_e178": {
    "primaryTargetElementId": "eDisposition.25",
    "source": "for each(\"eDisposition.HospitalTeamActivationGroup\")\nwhen not(any(undocumented(\"eDisposition.25\"), emptyPayload(\"eDisposition.25\")))\nrequire any(any(undocumented(\"eTimes.12\"), emptyPayload(\"eTimes.12\")), timeCompare(\"eDisposition.25\", \"same-or-before\", \"eTimes.12\"))"
  },
  "nemSch_e179": {
    "primaryTargetElementId": "eDisposition.25",
    "source": "for each(\"eDisposition.HospitalTeamActivationGroup\")\nwhen not(any(undocumented(\"eDisposition.25\"), emptyPayload(\"eDisposition.25\")))\nrequire timeCompare(\"eDisposition.25\", \"same-or-before\", \"eTimes.13\")"
  },
  "nemSch_e180": {
    "primaryTargetElementId": "eDisposition.27",
    "source": "for each(\"eDisposition.IncidentDispositionGroup\")\nrequire any(compareValue(\"eDisposition.27\", \"equal\", \"4227001\"), not(member(\"eDisposition.28\", \"4228001\", \"4228003\", \"4228005\", \"4228007\")))"
  },
  "nemSch_e181": {
    "primaryTargetElementId": "eDisposition.27",
    "source": "for each(\"eDisposition.IncidentDispositionGroup\")\nrequire any(compareValue(\"eDisposition.27\", \"equal\", \"4227001\"), not(member(\"eDisposition.29\", \"4229001\", \"4229003\", \"4229005\", \"4229007\")))"
  },
  "nemSch_e182": {
    "primaryTargetElementId": "eDisposition.27",
    "source": "for each(\"eDisposition.IncidentDispositionGroup\")\nrequire any(compareValue(\"eDisposition.27\", \"equal\", \"4227001\"), any(any(undocumented(\"eDisposition.30\"), emptyPayload(\"eDisposition.30\")), member(\"eDisposition.30\", \"4230011\", \"4230013\")))"
  },
  "nemSch_e183": {
    "primaryTargetElementId": "eDisposition.28",
    "source": "for each(\"eDisposition.IncidentDispositionGroup\")\nrequire any(not(any(undocumented(\"eDisposition.28\"), emptyPayload(\"eDisposition.28\"))), compareValue(\"eDisposition.27\", \"not-equal\", \"4227001\"))"
  },
  "nemSch_e184": {
    "primaryTargetElementId": "eDisposition.28",
    "source": "for each(\"eDisposition.IncidentDispositionGroup\")\nrequire any(compareValue(\"eDisposition.28\", \"equal\", \"4228001\"), not(member(\"eDisposition.29\", \"4229001\", \"4229003\", \"4229005\", \"4229007\")))"
  },
  "nemSch_e185": {
    "primaryTargetElementId": "eDisposition.29",
    "source": "for each(\"eDisposition.IncidentDispositionGroup\")\nwhen any(undocumented(\"eDisposition.29\"), emptyPayload(\"eDisposition.29\"))\nrequire compareValue(\"eDisposition.27\", \"not-equal\", \"4227001\")"
  },
  "nemSch_e186": {
    "primaryTargetElementId": "eDisposition.30",
    "source": "for each(\"eDisposition.IncidentDispositionGroup\")\nwhen any(undocumented(\"eDisposition.30\"), emptyPayload(\"eDisposition.30\"))\nrequire compareValue(\"eDisposition.27\", \"not-equal\", \"4227001\")"
  },
  "nemSch_e187": {
    "primaryTargetElementId": "eDisposition.32",
    "source": "when any(any(undocumented(\"eDisposition.32\"), emptyPayload(\"eDisposition.32\")), compareValue(\"eDisposition.32\", \"equal\", \"4232013\"))\nrequire compareValue(\"eDisposition.28\", \"not-equal\", \"4228001\")"
  }
} as const satisfies NemsisNormalizationTable;
