-- One-to-one restricted wide source with report identity for repeated analysis.
create view analytics.review_field_source_with_identity with (security_barrier = true) as
select p.organization_id, p.documenting_user_id, p.synthetic, p.reporting_date,
  jsonb_strip_nulls(jsonb_build_object(
    'eArrest.01',
    p.earrest_01,
    'eArrest.02',
    p.earrest_02,
    'eArrest.07',
    p.earrest_07,
    'eArrest.10',
    p.earrest_10,
    'eArrest.11',
    p.earrest_11,
    'eArrest.13',
    p.earrest_13,
    'eArrest.16',
    p.earrest_16,
    'eArrest.18',
    p.earrest_18,
    'eArrest.20',
    p.earrest_20,
    'eArrest.21',
    p.earrest_21,
    'eArrest.22',
    p.earrest_22,
    'eDispatch.01',
    p.edispatch_01,
    'eDispatch.02',
    p.edispatch_02,
    'eDispatch.05',
    p.edispatch_05,
    'eDisposition.04',
    p.edisposition_04,
    'eDisposition.05',
    p.edisposition_05,
    'eDisposition.06',
    p.edisposition_06,
    'eDisposition.08',
    p.edisposition_08,
    'eDisposition.11',
    p.edisposition_11,
    'eDisposition.16',
    p.edisposition_16,
    'eDisposition.17',
    p.edisposition_17,
    'eDisposition.19',
    p.edisposition_19,
    'eDisposition.21',
    p.edisposition_21,
    'eDisposition.22',
    p.edisposition_22,
    'eDisposition.27',
    p.edisposition_27,
    'eDisposition.28',
    p.edisposition_28,
    'eDisposition.29',
    p.edisposition_29,
    'eDisposition.30',
    p.edisposition_30,
    'eDisposition.32',
    p.edisposition_32,
    'eExam.01',
    p.eexam_01,
    'eExam.02',
    p.eexam_02,
    'eExam.21',
    p.eexam_21,
    'eHistory.16',
    p.ehistory_16,
    'eHistory.18',
    p.ehistory_18,
    'eInjury.06',
    p.einjury_06,
    'eInjury.09',
    p.einjury_09,
    'eInjury.21',
    p.einjury_21,
    'eInjury.23',
    p.einjury_23,
    'eInjury.25',
    p.einjury_25,
    'eOther.01',
    p.eother_01
  )) ||
  jsonb_strip_nulls(jsonb_build_object(
    'eOutcome.01',
    p.eoutcome_01,
    'eOutcome.02',
    p.eoutcome_02,
    'eOutcome.21',
    p.eoutcome_21,
    'ePatient.06',
    p.epatient_06,
    'ePatient.07',
    p.epatient_07,
    'ePatient.08',
    p.epatient_08,
    'ePatient.10',
    p.epatient_10,
    'ePatient.11',
    p.epatient_11,
    'ePatient.13',
    p.epatient_13,
    'ePatient.16',
    p.epatient_16,
    'ePatient.20',
    p.epatient_20,
    'ePatient.22',
    p.epatient_22,
    'ePatient.25',
    p.epatient_25,
    'ePayment.01',
    p.epayment_01,
    'ePayment.02',
    p.epayment_02,
    'ePayment.05',
    p.epayment_05,
    'ePayment.08',
    p.epayment_08,
    'ePayment.27',
    p.epayment_27,
    'ePayment.28',
    p.epayment_28,
    'ePayment.30',
    p.epayment_30,
    'ePayment.32',
    p.epayment_32,
    'ePayment.35',
    p.epayment_35,
    'ePayment.36',
    p.epayment_36,
    'ePayment.38',
    p.epayment_38,
    'ePayment.40',
    p.epayment_40,
    'ePayment.49',
    p.epayment_49,
    'ePayment.50',
    p.epayment_50,
    'ePayment.57',
    p.epayment_57,
    'eResponse.05',
    p.eresponse_05,
    'eResponse.06',
    p.eresponse_06,
    'eResponse.07',
    p.eresponse_07,
    'eResponse.23',
    p.eresponse_23,
    'eScene.01',
    p.escene_01,
    'eScene.06',
    p.escene_06,
    'eScene.07',
    p.escene_07,
    'eScene.08',
    p.escene_08,
    'eScene.09',
    p.escene_09,
    'eScene.17',
    p.escene_17,
    'eScene.18',
    p.escene_18,
    'eScene.21',
    p.escene_21
  )) ||
  jsonb_strip_nulls(jsonb_build_object(
    'eScene.22',
    p.escene_22,
    'eScene.23',
    p.escene_23,
    'eSituation.02',
    p.esituation_02,
    'eSituation.07',
    p.esituation_07,
    'eSituation.08',
    p.esituation_08,
    'eSituation.09',
    p.esituation_09,
    'eSituation.11',
    p.esituation_11,
    'eSituation.13',
    p.esituation_13,
    'eSituation.14',
    p.esituation_14,
    'eSituation.15',
    p.esituation_15,
    'eSituation.16',
    p.esituation_16,
    'eSituation.20',
    p.esituation_20
  )) as field_values,
  jsonb_strip_nulls(jsonb_build_object(
    'eArrest.01',
    p.element_statuses -> 'eArrest.01',
    'eArrest.02',
    p.element_statuses -> 'eArrest.02',
    'eArrest.07',
    p.element_statuses -> 'eArrest.07',
    'eArrest.10',
    p.element_statuses -> 'eArrest.10',
    'eArrest.11',
    p.element_statuses -> 'eArrest.11',
    'eArrest.13',
    p.element_statuses -> 'eArrest.13',
    'eArrest.16',
    p.element_statuses -> 'eArrest.16',
    'eArrest.18',
    p.element_statuses -> 'eArrest.18',
    'eArrest.20',
    p.element_statuses -> 'eArrest.20',
    'eArrest.21',
    p.element_statuses -> 'eArrest.21',
    'eArrest.22',
    p.element_statuses -> 'eArrest.22',
    'eDispatch.01',
    p.element_statuses -> 'eDispatch.01',
    'eDispatch.02',
    p.element_statuses -> 'eDispatch.02',
    'eDispatch.05',
    p.element_statuses -> 'eDispatch.05',
    'eDisposition.04',
    p.element_statuses -> 'eDisposition.04',
    'eDisposition.05',
    p.element_statuses -> 'eDisposition.05',
    'eDisposition.06',
    p.element_statuses -> 'eDisposition.06',
    'eDisposition.08',
    p.element_statuses -> 'eDisposition.08',
    'eDisposition.11',
    p.element_statuses -> 'eDisposition.11',
    'eDisposition.16',
    p.element_statuses -> 'eDisposition.16',
    'eDisposition.17',
    p.element_statuses -> 'eDisposition.17',
    'eDisposition.19',
    p.element_statuses -> 'eDisposition.19',
    'eDisposition.21',
    p.element_statuses -> 'eDisposition.21',
    'eDisposition.22',
    p.element_statuses -> 'eDisposition.22',
    'eDisposition.27',
    p.element_statuses -> 'eDisposition.27',
    'eDisposition.28',
    p.element_statuses -> 'eDisposition.28',
    'eDisposition.29',
    p.element_statuses -> 'eDisposition.29',
    'eDisposition.30',
    p.element_statuses -> 'eDisposition.30',
    'eDisposition.32',
    p.element_statuses -> 'eDisposition.32',
    'eExam.01',
    p.element_statuses -> 'eExam.01',
    'eExam.02',
    p.element_statuses -> 'eExam.02',
    'eExam.21',
    p.element_statuses -> 'eExam.21',
    'eHistory.16',
    p.element_statuses -> 'eHistory.16',
    'eHistory.18',
    p.element_statuses -> 'eHistory.18',
    'eInjury.06',
    p.element_statuses -> 'eInjury.06',
    'eInjury.09',
    p.element_statuses -> 'eInjury.09',
    'eInjury.21',
    p.element_statuses -> 'eInjury.21',
    'eInjury.23',
    p.element_statuses -> 'eInjury.23',
    'eInjury.25',
    p.element_statuses -> 'eInjury.25',
    'eOther.01',
    p.element_statuses -> 'eOther.01'
  )) ||
  jsonb_strip_nulls(jsonb_build_object(
    'eOutcome.01',
    p.element_statuses -> 'eOutcome.01',
    'eOutcome.02',
    p.element_statuses -> 'eOutcome.02',
    'eOutcome.21',
    p.element_statuses -> 'eOutcome.21',
    'ePatient.06',
    p.element_statuses -> 'ePatient.06',
    'ePatient.07',
    p.element_statuses -> 'ePatient.07',
    'ePatient.08',
    p.element_statuses -> 'ePatient.08',
    'ePatient.10',
    p.element_statuses -> 'ePatient.10',
    'ePatient.11',
    p.element_statuses -> 'ePatient.11',
    'ePatient.13',
    p.element_statuses -> 'ePatient.13',
    'ePatient.16',
    p.element_statuses -> 'ePatient.16',
    'ePatient.20',
    p.element_statuses -> 'ePatient.20',
    'ePatient.22',
    p.element_statuses -> 'ePatient.22',
    'ePatient.25',
    p.element_statuses -> 'ePatient.25',
    'ePayment.01',
    p.element_statuses -> 'ePayment.01',
    'ePayment.02',
    p.element_statuses -> 'ePayment.02',
    'ePayment.05',
    p.element_statuses -> 'ePayment.05',
    'ePayment.08',
    p.element_statuses -> 'ePayment.08',
    'ePayment.27',
    p.element_statuses -> 'ePayment.27',
    'ePayment.28',
    p.element_statuses -> 'ePayment.28',
    'ePayment.30',
    p.element_statuses -> 'ePayment.30',
    'ePayment.32',
    p.element_statuses -> 'ePayment.32',
    'ePayment.35',
    p.element_statuses -> 'ePayment.35',
    'ePayment.36',
    p.element_statuses -> 'ePayment.36',
    'ePayment.38',
    p.element_statuses -> 'ePayment.38',
    'ePayment.40',
    p.element_statuses -> 'ePayment.40',
    'ePayment.49',
    p.element_statuses -> 'ePayment.49',
    'ePayment.50',
    p.element_statuses -> 'ePayment.50',
    'ePayment.57',
    p.element_statuses -> 'ePayment.57',
    'eResponse.05',
    p.element_statuses -> 'eResponse.05',
    'eResponse.06',
    p.element_statuses -> 'eResponse.06',
    'eResponse.07',
    p.element_statuses -> 'eResponse.07',
    'eResponse.23',
    p.element_statuses -> 'eResponse.23',
    'eScene.01',
    p.element_statuses -> 'eScene.01',
    'eScene.06',
    p.element_statuses -> 'eScene.06',
    'eScene.07',
    p.element_statuses -> 'eScene.07',
    'eScene.08',
    p.element_statuses -> 'eScene.08',
    'eScene.09',
    p.element_statuses -> 'eScene.09',
    'eScene.17',
    p.element_statuses -> 'eScene.17',
    'eScene.18',
    p.element_statuses -> 'eScene.18',
    'eScene.21',
    p.element_statuses -> 'eScene.21'
  )) ||
  jsonb_strip_nulls(jsonb_build_object(
    'eScene.22',
    p.element_statuses -> 'eScene.22',
    'eScene.23',
    p.element_statuses -> 'eScene.23',
    'eSituation.02',
    p.element_statuses -> 'eSituation.02',
    'eSituation.07',
    p.element_statuses -> 'eSituation.07',
    'eSituation.08',
    p.element_statuses -> 'eSituation.08',
    'eSituation.09',
    p.element_statuses -> 'eSituation.09',
    'eSituation.11',
    p.element_statuses -> 'eSituation.11',
    'eSituation.13',
    p.element_statuses -> 'eSituation.13',
    'eSituation.14',
    p.element_statuses -> 'eSituation.14',
    'eSituation.15',
    p.element_statuses -> 'eSituation.15',
    'eSituation.16',
    p.element_statuses -> 'eSituation.16',
    'eSituation.20',
    p.element_statuses -> 'eSituation.20'
  )) as field_absences,
  p.report_id
from analytics_private.epcr p;

revoke all on analytics.review_field_source_with_identity from public, anon, authenticated,
  open_triage_analyst, open_triage_identified_analyst;
grant select on analytics.review_field_source_with_identity to open_triage_api_runtime;
comment on view analytics.review_field_source_with_identity is
  'API-only, catalog allowlisted signed report source with report identity for repeated Review BI.';

-- Review's repeatable source is restricted to non-identifying, structured standard fields.
-- The API still applies organization, dataset, author, and date predicates on every query.
create view analytics.review_repeated_field_source with (security_barrier = true) as
select p.organization_id, p.documenting_user_id, p.synthetic, p.reporting_date,
  r.report_id, r.element_id, r.element_occurrence_id, r.group_id, r.group_instance_id,
  r.parent_group_instance_id, r.group_ordinal, r.element_ordinal,
  r.clinical_time, r.clinical_time_element_id, r.documented_time,
  r.value_kind, r.code, r.absence_kind, r.absence_code,
  coalesce(r.normalized_numeric, r.value_numeric, r.value_integer::numeric) as numeric_value,
  coalesce(r.normalized_unit_code, r.source_unit_code,
    case when r.element_id = 'eMedications.05' then dosage_unit.code end,
    case when r.element_id = 'eVitals.06' then 'mm[Hg]' end) as unit_code,
  r.normalization_rule_id, r.quality_flags
from analytics_private.epcr_repeatable_element r
join analytics.review_field_source_with_identity p on p.report_id = r.report_id and p.reporting_date = r.reporting_date
  and p.organization_id = r.organization_id
left join lateral (
  select u.code from analytics_private.epcr_repeatable_element u
  where r.element_id = 'eMedications.05' and u.report_id = r.report_id
    and u.reporting_date = r.reporting_date and u.group_instance_id = r.group_instance_id
    and u.element_id = 'eMedications.06' and not u.is_identifying
  order by u.element_ordinal, u.element_occurrence_id limit 1
) dosage_unit on true
where not r.is_identifying
  and r.element_id in ('eMedications.03', 'eMedications.05', 'eVitals.06');

revoke all on analytics.review_repeated_field_source from public, anon, authenticated,
  open_triage_analyst, open_triage_identified_analyst;
grant select on analytics.review_repeated_field_source to open_triage_api_runtime;
comment on view analytics.review_repeated_field_source is
  'API-only effective signed repeated standard values for basic Review BI; one row per occurrence.';
